name: Send repository dispatch event

on:
  workflow_dispatch:

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    steps:

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          repository: stiagoq/serenity_prueba_tyba
          event-type: my-event
          client-payload: '{"github": ${{ toJson(github) }}}'

      - name: Comfirn event
        run: |
          curl -H "Authorization: Bearer ${{ secrets.REPOSITORY_ACCESS_TOKEN }}" \
           -H "Accept: application/vnd.github.v3+json" \
           https://api.github.com/repos/stiagoq/serenity_prueba_tyba/events
