name: Trigger Serenity Test

on:
  push:
    branches:
      - main

jobs:
  trigger_serenity:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Serenity 
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"on-demand-test","client_payload":{"unit":false,"integration":true}}'
