name: Build Artifacts

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: call the other repo
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        EVENT: push
        ORG: stiagoq
        REPO: serenity_prueba_tyba
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer 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" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/OWNER/REPO/dispatches \
          -d '{"event_type":"on-demand-test","client_payload":{"unit":false,"integration":true}}'
