name: Send repository dispatch event

on:
  workflow_dispatch:

jobs:
  trigger_serenity:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Serenity project
        run: |
          curl -i -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/stiagoq/serenity_prueba_tyba/dispatches \
          -d '{"event_type":"on-demand-test","client_payload":{"unit":false,"integration":true}}'
