name: Send repository dispatch event

on:
  workflow_dispatch:

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    steps:
      - name: Fire event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPOSITORY_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/stiagoq/serenity_prueba_tyba/dispatches \
            -d '{"event_type":"dispatch-event"}'

      - name: Comfirn event
        run: |
          curl -H "Authorization: Bearer ${{ secrets.REPOSITORY_ACCESS_TOKEN }}" \
           -H "Accept: application/vnd.github.v3+json" \
           https://api.github.com/repos/stiagoq/serenity_prueba_tyba/events
