name: Send repository dispatch event

on:
  push:

jobs:
  trigger_serenity:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Serenity project
        run: |
          curl --location 'https://api.github.com/repos/stiagoq/prueba_salesforce_sereniy/actions/workflows/ensayo.yml/dispatches' \
          --header 'X-GitHub-Api-Version: 2022-11-28' \
          --header 'Accept: application/vnd.github+json' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ secrets.REPOSITORY_ACCESS_TOKEN }}' \
          --data '{
              "ref":"main"
          }'
